server:
  servlet:
    context-path: /
  port: 8080

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.92.229.147:3306/timeset?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  mapper-locations: classpath*:mapping/*Mapper.xml
  type-aliases-package: com.timeset
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    ##showSql

#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql


